-- 적절한 집계함수를 찾아서 nvl 함수 대신 적용
SELECT MAX(MGR) AS MGR
FROM EMP
WHERE ENAME = 'JSC';

-- 집계함수를 인수로 한 NVL/ISNULL 함수를 이용해서 공집합인 경우에도 빈칸이 아닌 9999로 출력
SELECT NVL (MAX (MGR), 9999) AS MGR
FROM EMP
WHERE ENAME = 'JSC';

-- 사원 테이블에서 MGR와 7698이 같으면 NULL을 표시, 같지 않으면 MGR 표시
SELECT ENAME, EMPNO, MGR, NULLIF (MGR, 7698) AS NUIF
FROM EMP;

SELECT ENAME, EMPNO, MGR,
    CASE
    WHEN MGR = 7698 THEN NULL
    ELSE MGR
    END AS NUIF
FROM EMP;

-- COALESCE 함수는 두 개의 중첩된 CASE 문장으로 표현 가능
SELECT ENAME, COMM, SAL, 
    CASE
    WHEN COMM IS NOT NULL THEN COMM
    ELSE (CASE WHEN SAL IS NOT NULL THEN SAL ELSE NULL END)
    END AS COAL
FROM EMP;

