-- 케이이그 소속 선수 중 삼성블루윙즈 팀인 선수이면서 포지션이 골키퍼인 선수들의 집합
SELECT TEAM_ID AS 팀코드, PLAYER_NAME AS 선수명, POSITION AS 포지션, BACK_NO AS 백넘버, HEIGHT AS 키 
FROM PLAYER A
WHERE TEAM_ID = 'K02'
INTERSECT
SELECT TEAM_ID AS 팀코드, PLAYER_NAME AS 선수명, POSITION AS 포지션, BACK_NO AS 백넘버, HEIGHT AS 키 
FROM PLAYER A
WHERE POSITION = 'GK'
ORDER BY 1, 2, 3, 4, 5;

SELECT B.DNAME, A.JOB, COUNT(*) AS EMP_CNT, SUM(A.SAL) AS SAL_SUM
FROM EMP A, DEPT B
WHERE B.DEPTNO = A.DEPTNO
GROUP BY B.DNAME, A.JOB;

-- 부서명과 업무명을 기준으로 집계한 일반적인 GROUP BY SQL 문장에 ROLL UP 함수 사용
SELECT B.DNAME, A.JOB, COUNT(*) AS EMP_CNT, SUM(A.SAL) AS SAL_SUM
FROM EMP A, DEPT B
WHERE B.DEPTNO = A.DEPTNO
GROUP BY ROLLUP (B.DNAME, A.JOB);

-- ROLLUP 함수를 추가한 집계 보고서에서 집계 레코드를 구분할 수 있는 GROUPING 함수가 추가된 SQL 문장
SELECT B.DNAME, GROUPING(B.DNAME) AS DNAME_GRP,
       A.JOB, GROUPING (A.JOB ) AS JOB_GRP,
       COUNT(*) AS EMP_CNT, SUM(A.SAL) AS SAL_SUM
FROM EMP A, DEPT B
WHERE B.DEPTNO = A.DEPTNO
GROUP BY ROLLUP (B.DNAME, A.JOB)
ORDER BY B.DNAME, A.JOB;