CREATE TABLE courseDetail (

    BDNUM VARCHAR2(8) NOT NULL, --게시글 넘버

    BDTITLE VARCHAR2(100) NOT NULL, -- 게시글제목

    CONTENT VARCHAR2(4000) NOT NULL, -- 게시글내용

    WRITER VARCHAR2(30) NOT NULL, -- 작성자

    REGDATE DATE NOT NULL, -- 등록날짜

    CONSTRAINT PK_BOARD PRIMARY KEY(BDNUM) -- PK설정
);

COMMIT;