CREATE TABLE WFAVORITE( 
chartNUM NUMBER(4) NOT NULL PRIMARY KEY, 
CLASSNUM NUMBER(4),
CLASSNAME VARCHAR2(200),
userid varchar2(50),
FOREIGN KEY (CLASSNUM)
REFERENCES WCLASS(CLASSNUM) 
    );
    
SELECT
    *
FROM WFAVORITE;

commit;
--DROP TABLE wcart;


